name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  run-typescript-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install modules
        run: yarn

      - name: Run ts-coverage
        run: yarn ts-coverage -o coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: typescript
          name: typescript
          # project specific codecov token
          token: ${{ secrets.CODECOV_TOKEN }}
